---
title: "Layer_exp"
format: html
editor: visual
---

## Load Package and data. The data has been cleaned

```{r}
library(tidyverse)
library(janitor)
My_data <-  readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-24/lemur_data.csv')

My_data <- My_data |> 
  clean_names()
```



Visualize the data distribution on Bar_Chart based on the basic class (taxon)
```{r}
My_data |> 
  ggplot(aes(y=fct_infreq(taxon), fill=birth_type)) +
  labs(y = "Taxon of lemur", x = "Lemur taxon Count", 
       title = "Distribution of lemur taxon showing the type of birth",
       caption = "Birth Type: captive-born (CB), wild-born (WB) and unknown (UNK)") +
  geom_bar() 
```
Let us restrict our search to those born at the Duke Lemur Center.
```{r}
my_data <- 
  My_data |>
  filter(birth_institution == "Duke Lemur Center")
```

```{r}
my_data |> 
  group_by(taxon) |> 
  sample_n(100) |> 
  ggplot(aes(x= age_at_wt_d, y= weight_g)) +
  geom_point(aes(color = hybrid)) +
  geom_smooth(method = 'loess', formula = 'y ~ x') +
  facet_wrap(~taxon)
```

```{r}
my_data |> 
    filter(age_at_wt_y >= 2 & age_at_wt_y <=6) |> 
  group_by(taxon) |> 
  slice_sample(n=14) |> 
  summarise(Avg = mean(weight_g), n=n()) |> 
  ggplot(aes(x=Avg, y= fct_reorder(taxon, Avg))) +
  geom_col()
```

```{r}
my_data |> 
    filter(age_category == "IJ" | age_category == "young_adult") |> 
  group_by(taxon) |> 
#  slice_sample(n=10) |> 
  summarise(Avg = mean(weight_g), n=n()) |> 
  arrange(Avg) #Dont forget about weight at birth

```

```{r}
my_data |> 
  filter(age_category == "IJ" | age_category == "young_adult") |> 
  group_by(taxon) |> 
  slice_sample(n = 27) |> 
  summarise(Avg = mean(weight_g)) |> 
  ggplot(aes(x=Avg, y= fct_reorder(taxon, Avg))) +
  geom_col()
```

```{r}
my_data |> 
  filter(age_category == "IJ" | age_category == "young_adult") |> 
  group_by(taxon) |> 
  slice_sample(n = 27) |> 
  summarise(Avg = mean(weight_g), n=n()) #Not Ordered
```

```{r}
my_data |> 
  count(expected_gestation)
```

```{r}
my_data |> 
  slice_sample(n= 1, by = taxon) |>
  select(taxon, expected_gestation) |> 
# distinct(expected_gestation, .keep_all = TRUE) |> 
  arrange(expected_gestation)
```

```{r}
y <-  my_data |>
  filter(age_at_wt_d == 0) |>
  group_by(taxon) |> 
  summarise(Avg_g = mean(expected_gestation), Avg_w = mean(weight_g), 
            sc = mean(sire_age_at_concep_y)) |> 
  arrange(taxon)
```

```{r}
x <- my_data |> 
  filter(age_category == "IJ" | age_category == "young_adult") |> 
  group_by(taxon) |> 
  slice_sample(n = 27) |> 
  summarise(Avg = mean(weight_g)) |> 
  arrange(taxon)
```

```{r}
#put all data frames into list
text <- list(x,y)      

#merge all data frames together
text |> reduce(full_join, by='taxon')
```

```{r}
tex = merge(x,y, by='taxon')
```

```{r}
tex
```

```{r}
  tex |> 
    ggplot(aes(Avg, Avg_w,label = taxon)) +
  geom_point() +
  geom_label()
```

```{r}
my_data |> 
  filter(age_at_wt_d == 0 & taxon == "PCOQ") |> 
  select(taxon, age_at_wt_d, weight_g, sire_age_at_concep_y) |> 
  ggplot(aes(x= weight_g, y = sire_age_at_concep_y, color =taxon)) +
  geom_point()
```

```{r}
my_data |> 
  filter(sex == "F" & (age_category == "adult" ) & !is.na(n_known_offspring)) |> 
  group_by(taxon) |> 
  slice_sample(n = 10) |> 
  summarise(x = sum(n_known_offspring),y = mean(r_min_dam_age_at_concep_y), n=n()) |> 
  ggplot(aes(x,y)) +
  geom_point()
```

```{r}
my_data |> 
  group_by(taxon) |> 
  slice_head(n = 2) |> 
  relocate(r_min_dam_age_at_concep_y, .before = dlc_id)
```

```{r}
my_data |> 
#filter((age_category == "IJ" | age_category == "young_adult") & (taxon %in% c("PCOQ", "VVV", "MMUR", "GMOH"))) |>
  filter((age_at_wt_y >= 2 & age_at_wt_y <=6) & (taxon %in% c("PCOQ", "VVV", "MMUR", "GMOH"))) |> 
  group_by(taxon) |> 
  slice_sample(n=14) |> 
  relocate(sex, age_at_wt_y, weight_g, .after = taxon) |> 
  ggplot(aes(x = taxon, y=weight_g)) +
  geom_boxplot()
  
  #select(taxon, sex, age_at_wt_d, weight_g) |> 
  
```

```{r}
my_data |> 
    
#filter((age_category == "IJ" | age_category == "young_adult") & (taxon %in% c("PCOQ", "VVV", "MMUR", "GMOH"))) |>
  filter((age_at_wt_y >= 2 & age_at_wt_y <=6) & (taxon %in% c("PCOQ", "VVV"))) |> 
  group_by(taxon) |> 
  slice_sample(n=14) |> 
  relocate(sex, age_at_wt_y, weight_g, .after = taxon)  |> 
  ggplot(aes(x = taxon, y=weight_g, color = sex)) +
  geom_boxplot()
```

```{r}
my_data |> 
    filter((age_at_wt_y >= 2 & age_at_wt_y <=6) & taxon == "MMUR") |> 
  ggplot(aes(x = weight_g)) +
  geom_histogram(bins = 30)
```

```{r}
 my_data |> 
    #filter(age_category == "young_adult" & taxon == "PCOQ") |> 
    filter((age_at_wt_y >= 2 & age_at_wt_y <=3) & taxon == "PCOQ") |> 
  ggplot(aes(x = weight_g)) +
  geom_histogram(binwidth = 120)
```
