---
title: "Excercises"
format: html
editor: visual
---

```{r}
library(palmerpenguins)
library(tidyverse)
library(ggthemes)
```

```{r}
penguins |>
  ggplot(mapping = aes(x=bill_length_mm, y=bill_depth_mm )  ) +
  geom_point()
```

```{r}
penguins |>
  ggplot(mapping = aes(x=species, y=bill_depth_mm )  ) +
  geom_boxplot() +
  geom_jitter(width = 0.1, aes(color = species)) +
  scale_color_colorblind()
```

```{r}
penguins |>
  ggplot() + #na.rm eliminate the na in the data
  labs(x="The Bill_Lenght", y = "The Body_Mass", title = "The RTS Of Mass and Bill",          subtitle = "Check it out", tag = "THE MAP") +
  geom_point(aes(x = body_mass_g, y=bill_depth_mm), na.rm = TRUE)
```

```{r}
ggplot(data=penguins, aes(body_mass_g, flipper_length_mm))+
  geom_point(aes(color=bill_depth_mm), na.rm=TRUE) +
  geom_smooth(na.rm = TRUE)
```

```{r}
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point() +
  geom_smooth(se = FALSE, aes(color = island))
```

```{r}
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = island)
) +
  geom_point() +
  geom_smooth(se = FALSE)

```

```{r}
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point() +
  geom_smooth()

```

```{r}

ggplot() +
  geom_point(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  ) +
  geom_smooth(
    data = penguins,
    mapping = aes(x = flipper_length_mm, y = body_mass_g)
  )
```

```{r}
penguins |>
  ggplot(aes(fct_infreq(species)))+
  geom_bar()
```

```{r}
penguins |>
  ggplot(aes(fct_rev(fct_infreq(species))))+
  geom_bar()
```

```{r}
ggplot(penguins, aes(body_mass_g))+
  geom_histogram(binwidth = 200, na.rm = TRUE)
```

```{r}
ggplot(penguins, aes(body_mass_g))+
  geom_histogram(binwidth = 200, na.rm = TRUE)
```

```{r}
ggplot(penguins, aes(body_mass_g))+
  geom_density(na.rm = TRUE)
```

```{r}
ggplot(penguins, aes(body_mass_g, color= species))+
  geom_density(na.rm = TRUE, linewidth= 1)
```

```{r}
ggplot(penguins, aes(body_mass_g, fill= species))+
  geom_density(alpha =0.3, na.rm = TRUE)
```

```{r}
penguins |>
  ggplot(aes(y=species)) +
  geom_bar()
```

```{r}
ggplot(penguins, aes(x = species)) +
  geom_bar(color = "red")

ggplot(penguins, aes(x = species)) +
  geom_bar(fill = "red")
```

```{r}
diamonds |>
  ggplot(aes(x=carat)) +
  geom_histogram(binwidth =0.5)
```

```{r}
diamonds |>
  arrange(desc(carat))
```

```{r}
penguins |>
  ggplot(aes(x=fct_infreq(species), fill = island)) +
  geom_bar(na.rm = TRUE, position = 'fill')
```

```{r}
penguins |>
  ggplot(mapping = aes(x=body_mass_g, y=flipper_length_mm, color = species, shape = species)) +
  geom_point() +
  facet_wrap('island')
```

```{r}
mpg |>
  ggplot(aes(x=hwy, y=displ)) +
  geom_point(aes(size = year, color = cyl, shape =class))

```

```{r}
mpg |>
  ggplot(aes(x=hwy, y=displ, linewidth =year)) +
  geom_point()

```

```{r}
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm,
    color = species, shape = species
  )
) +
  geom_point() 
```

```{r}
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(position = "fill")

```

```{r}
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = "fill") 
  ggsave("My_bar_plot.jpg")
```

```{r}
ggplot(mpg, aes(x = class)) +
  geom_bar()
ggplot(mpg, aes(x = cty, y = hwy)) +
  geom_point()
ggsave("mpg-plot.png")
```

```{r}
ggplot(penguins, aes(x=body_mass_g , y=flipper_length_mm )) +
  geom_point(aes( colour= species, shape = species)) +
  labs(x='The Body Mass', y='The Flipper Length', 
       title = 'The Penguine Body and Flipper RTS', 
       subtitle = "It shows the relationship between BodyMass and Flipper") +
  geom_smooth(method = "lm") +
  scale_color_colorblind()
```
